### ISSUE TITLE
模型参数大小的问题

### ISSUE THREAD

**Issue by Liqq1** [bubbliiiing/classification-pytorch#10]
您好，训练出来的ResNet50 的pth大小为92161kb；
但是作者原文中写的25.6M，这是什么原因呀？
<img width="636" alt="image" src="https://user-images.githubusercontent.com/54054113/170653934-57f3d9db-e95f-47c6-9f0d-af30923f6239.png">

**Comment by bubbliiiing** [comment]
有没有一种可能，pth是存储空间？

**Comment by Liqq1** [comment]
请问有什么方法可以统计参数量吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bubbliiiing ***@***.***&gt;
发送时间: 2022年5月27日 21:13
收件人: bubbliiiing/classification-pytorch ***@***.***&gt;
抄送: machine no learning ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bubbliiiing/classification-pytorch] 模型参数大小的问题 (Issue #10)

**Comment by bubbliiiing** [comment]
summary.py

**Comment by Liqq1** [comment]
> summary.py

我试了一下，其他都可以出来，但是vit会报如下的错(256x256时候会有，但224的时候不会报错)，是什么原因呀？
但我在train的时候可以用256x256的大小train vit
![04E8975528C3D706D42E1A0E560A3B57](https://user-images.githubusercontent.com/54054113/170909259-02caebf1-8a50-46ae-9fb2-043997f5b9fb.png)

**Comment by Liqq1** [comment]
> vit也有个input shape要设置

好的，那在train的时候不需要专门到vit里面设置是因为train里面的input_shape=[x,x]会覆盖vit中的吗？

还有就是我得出的结果和ResNet原文中不一样，是因为图像的输入大小和num_classes不一样吗？

**Comment by Liqq1** [comment]
> 

差距还挺大的，ResNet50 跑出来是86M，文章里写的25.6M
我的大小是(3,256,256) 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/54054113/172032733-992d033a-72e1-42b9-8705-59e73280d523.png">

**Comment by bubbliiiing** [comment]
你不知道哪个是参数量？

**Comment by Liqq1** [comment]
> 你不知道哪个是参数量？

啊？我知道吧…… 就是下面的Params size
![Uploading image.png…]()

图上是vit的结果；然后我跑resnet50的时候是86M

**Comment by Liqq1** [comment]
> 你不知道哪个是参数量？

啊？我知道吧…… 就是下面的Params size
![image](https://user-images.githubusercontent.com/54054113/172279193-7da7504c-cb00-4c04-8567-048ffd1e1d21.png)

图上是vit的结果；然后我跑resnet50的时候是86M

**Comment by bubbliiiing** [comment]
是total params…

**Comment by Liqq1** [comment]
> 是total params…
嗷嗷好的 ,那就是用这里的total params/1024/1024 得到最后的MB ，是吗？
![39FEA6AF0A85C644D0BFF36735179F06](https://user-images.githubusercontent.com/54054113/172858545-d2141bb6-8f64-4568-99fe-518e838937f3.png)

**Comment by Liqq1** [comment]
> 直接/1e6应该，不用1024好像。

好的谢谢，了解了👌
