### ISSUE TITLE
输入图像对于所有类别的属于可能性的问题

### ISSUE THREAD

**Issue by zhoujiayi1017** [bubbliiiing/classification-pytorch#15]
比如说输入img/cat.jpg的时候，预测结果是Class: cat Probability: 0.998，希望可以得到的预测结果是Class: cat Probability: 0.998，dog  Probability: 0.002。

#---------------------------------------------------#
#   获得所属种类
#---------------------------------------------------#
class_name  = self.class_names[np.argmax(preds)]
probability = np.max(preds)

我觉得应该是需要修改这块的代码，但是不知道该如何下手...初学者还请多多包涵~
如果能回复我，将不胜感激~~~支持大佬！！！

**Comment by bubbliiiing** [comment]
……一般不会这样做，因为类别很多

**Comment by bubbliiiing** [comment]
文字会很长

**Comment by zhoujiayi1017** [comment]
> 文字会很长

好吧🥹打算是做一个四类别的分类器，因为输入的都是CT图像，各类别的差异不大，所以想比较看看各类别的所属概率…我自己再研究一下好啦！谢谢大佬回复！

**Comment by bubbliiiing** [comment]
好的……加油，好好看一下呢，做个循环节就可以呃
