### ISSUE TITLE
关于resnet50在不同torchvision下的不同权重问题

### ISSUE THREAD

**Issue by babyta** [bubbliiiing/classification-pytorch#2]
https://download.pytorch.org/models/resnet50-19c8e357.pt
https://download.pytorch.org/models/resnet50-0676ba61.pth
我想问下这俩权重为啥不一样，我找到torchvision下的resnet.py文件。发现他们定义的网络结构一样的。为啥加载模型会不一样呢。
要是加载不对应的权重会报错：
RuntimeError: Error(s) in loading state_dict for ResNet:
        size mismatch for layer1.0.downsample.1.weight: copying a param with shape torch.Size([256, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for layer2.0.downsample.1.weight: copying a param with shape torch.Size([512, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for layer3.0.downsample.1.weight: copying a param with shape torch.Size([1024, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for layer4.0.downsample.1.weight: copying a param with shape torch.Size([2048, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([2048]).
求大佬指导。

**Comment by bubbliiiing** [comment]
这个问题我感觉应该在pytorch那边提……我不是那么了解

**Comment by babyta** [comment]
好的
