### ISSUE TITLE
迭代到50之后就停止了

### ISSUE THREAD

**Issue by Tokymin** [bubbliiiing/classification-pytorch#3]
代码在训练到50个epoch之后就停止了
![Uploading 图片.png…]()
报错是
`Total Loss: 0.733 || Val Loss: 0.695 
Epoch 51/100:   0%|          | 0/18 [00:00<?, ?it/s<class 'dict'>]Start Train

Process finished with exit code -1073741819 (0xC0000005)`
请问这是什么原因呢？

**Comment by Tokymin** [comment]
![图片](https://user-images.githubusercontent.com/32712253/156714072-5f216105-7fb0-4557-a8bc-1a568c8c85f5.png)

**Comment by Tokymin** [comment]
原来是我cuda 版本没对，以及解决啦

**Comment by bubbliiiing** [comment]
0 0，没装对居然可以50代

**Comment by Tokymin** [comment]
@bubbliiiing 哈哈，下的92的版本，可以跑50代哈哈，后面百度了下说是这个版本问题，又给换成10.的版本就没问题了

**Comment by bubbliiiing** [comment]
载入当时的权值就可以

> > 0 0，没装对居然可以50代
> 
> 您好，想问一下，训练因为显存问题中断，怎么在中断的点，继续训练呢，

**Comment by hj-monster** [comment]
我的也是51代出现了问题，中断了，报错的是：RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

我看网上说可能是版本不匹配，我检查了下我装的torch版本和cuda版本是匹配的
![图片](https://user-images.githubusercontent.com/79952577/166723191-443ecddb-4566-4fac-981a-d3d0f4fd91dd.png)

**Comment by hj-monster** [comment]
![图片](https://user-images.githubusercontent.com/79952577/166723424-250bf0cb-5208-4eef-a768-213270f27c07.png)

**Comment by Bug-CUDA** [comment]
> 解决啦，前50个epoch和后50个epoch的batchsize设置的一样32，前50个能带动，后50个epoch就带不动了，batchsize改成了16就可以啦，好像是这么个意思

RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
我是这个报错，一轮都进行不了，cuda10.0，cudnn7.4.1，batchsize16、8、4都试了，还没有解决
