### ISSUE TITLE
请问在训练时使用数据增强策略了吗？

### ISSUE THREAD

**Issue by Liqq1** [bubbliiiing/classification-pytorch#8]

**Comment by bubbliiiing** [comment]
当然。

**Comment by Liqq1** [comment]
请问数据增强部分的具体代码在哪里呀？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bubbliiiing ***@***.***&gt;
发送时间: 2022年5月14日 22:00
收件人: bubbliiiing/classification-pytorch ***@***.***&gt;
抄送: machine no learning ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bubbliiiing/classification-pytorch] 请问在训练时使用数据增强策略了吗？ (Issue #8)

**Comment by Liqq1** [comment]
> 当然。

看到了，谢谢
