### ISSUE TITLE
关于DataGenerator的问题

### ISSUE THREAD

**Issue by Liqq1** [bubbliiiing/classification-pytorch#9]
您好，我想问一下，这下面的两个参数True和False是代表DataGenerator类中的ramdom的值吗？
也就是autoagument一直是默认值True
![9372940FB7D066844E577AEE62524E11](https://user-images.githubusercontent.com/54054113/168471670-f114dd80-07f8-4d3a-a59d-f50cd1b5a652.png)
![D0C57D01BEF10340A466E3BC5A83BDF3](https://user-images.githubusercontent.com/54054113/168471688-48f4ade3-2010-4c67-8f05-26115d34cb3c.png)

**Comment by bubbliiiing** [comment]
对
